Update README and adapt script for other users

diff --git a/FastSim_NanoAOD_to_NN/get_all_NanoAODSIM_to_data2 b/FastSim_NanoAOD_to_NN/get_all_NanoAODSIM_to_data2
--- a/FastSim_NanoAOD_to_NN/get_all_NanoAODSIM_to_data2
+++ b/FastSim_NanoAOD_to_NN/get_all_NanoAODSIM_to_data2
@@ -1,17 +1,30 @@
 #!/bin/bash
 
-mkdir -p /data2/ltorterotot/ML/FastSim_NanoAOD_to_NN
-cd /data2/ltorterotot/ML/FastSim_NanoAOD_to_NN
+lyoservusername="torterotot"
+while getopts ":u:" opt
+do
+    case $opt in
+        u) lyoservusername=="-$OPTARG"
+           shift
+           shift
+           ;;
+        \?) echo "Invalid option -$OPTARG" >&2
+            ;;
+    esac
+done
+
+mkdir -p /data2/${USER}/ML/FastSim_NanoAOD_to_NN
+cd /data2/${USER}/ML/FastSim_NanoAOD_to_NN
 
 find . -type f -iname \*.txt -delete
 find . -type f -iname \*.h5 -delete
 find . -type f -iname Htt_merged_\* -delete
 
-rsync -au --progress torterotot@lyoserv.in2p3.fr:/gridgroup/cms/htt/shared_files/Data/NanoAODSIM/nevents_* /data2/ltorterotot/ML/FastSim_NanoAOD_to_NN/
+rsync -au --progress ${lyoservusername}@lyoserv.in2p3.fr:/gridgroup/cms/htt/shared_files/Data/NanoAODSIM/nevents_* /data2/${USER}/ML/FastSim_NanoAOD_to_NN/
 
-for d in $(ls /data2/ltorterotot/ML/FastSim_NanoAOD_to_NN | grep -ve ALL)
+for d in $(ls /data2/${USER}/ML/FastSim_NanoAOD_to_NN | grep -ve ALL)
 do
-    cd /data2/ltorterotot/ML/FastSim_NanoAOD_to_NN/$d
+    cd /data2/${USER}/ML/FastSim_NanoAOD_to_NN/$d
 
     for f in $(ls | grep Htt_.*_NanoAODSIM.root)
     do
